version: 0.2

phases:
  pre_build:
    commands:
      - "echo Logging in to Amazon ECR..."
      - "ECR_REGISTRY=448923944643.dkr.ecr.ca-central-1.amazonaws.com"
      - "ECR_REPO=${ECR_REGISTRY}/allen-assignment3"
      - "echo ECR_REGISTRY=${ECR_REGISTRY}"
      - "echo ECR_REPO=${ECR_REPO}"
      - "aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}"

  build:
    commands:
      - "echo Build started on $(date)"
      - "echo Building Docker image..."
      - "docker build -t allen-assignment3:latest ."
      - "echo Tagging Docker image for ECR..."
      - "docker tag allen-assignment3:latest ${ECR_REPO}:latest"

  post_build:
    commands:
      - "echo Build completed on $(date)"
      - "echo Pushing image to ECR..."
      - "docker push ${ECR_REPO}:latest"
      - "echo Creating imagedefinitions.json for ECS deploy..."
      - "printf '[{\"name\":\"allen-assignment3-container\",\"imageUri\":\"%s\"}]\\n' \"${ECR_REPO}:latest\" > imagedefinitions.json"
      - "echo imagedefinitions.json contents:"
      - "cat imagedefinitions.json"

artifacts:
  files:
    - imagedefinitions.json
