version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "allen-assignment3"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Starting pre-build..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query account --output text)
      - REGION=${AWS_DEFAULT_REGION:-$AWS_REGION}
      - if [ -z "$REGION" ]; then REGION="ca-central-1"; fi
      - ECR_REGISTRY=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - ECR_REPO=${ECR_REGISTRY}/${IMAGE_REPO_NAME}
      - echo "ECR registry: $ECR_REGISTRY"
      - echo "ECR repo: $ECR_REPO"
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building Docker image..."
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - echo "Tagging image for ECR..."
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing image to ECR..."
      - docker push ${ECR_REPO}:${IMAGE_TAG}
      - echo "Creating imagedefinitions.json for ECS deploy..."
      - printf '[{"name":"allen-assignment3-container","imageUri":"%s"}]\n' "${ECR_REPO}:${IMAGE_TAG}" > imagedefinitions.json
      - echo "imagedefinitions.json contents:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
